Test พี่เขา

In [11]:
from HW3_utils import FKHW3
import numpy as np
import math
q = [0,0,0]


In [23]:
R,P,R_e,p_e = FKHW3(q)

print(f"R : {R},\n P : {P},\n R_e : {R_e},\n p_e : {p_e}")

print("=========================================")
print(f"R_i : {R[:,:,3]}")

print("=========================================")
print(f"P_i : {P[:,3]}")
print("=========================================")
print(f"P_i : {p_e-P[:,2]}")

R : [[[-1.0000000e+00 -1.0000000e+00 -1.0000000e+00  6.1232343e-17]
  [-1.2246469e-16 -7.4987988e-33 -7.4987988e-33  6.1232343e-17]
  [ 0.0000000e+00  1.2246469e-16  1.2246469e-16  1.0000000e+00]]

 [[ 1.2246469e-16  1.2246469e-16  1.2246469e-16  1.0000000e+00]
  [-1.0000000e+00 -6.1232343e-17 -6.1232343e-17 -1.2246469e-16]
  [ 0.0000000e+00  1.0000000e+00  1.0000000e+00 -6.1232343e-17]]

 [[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.2246469e-16]
  [ 0.0000000e+00  1.0000000e+00  1.0000000e+00  1.0000000e+00]
  [ 1.0000000e+00  6.1232343e-17  6.1232343e-17 -6.1232343e-17]]],
 P : [[ 0.0000000e+00  0.0000000e+00  4.2500000e-01  8.9943000e-01]
 [ 0.0000000e+00  0.0000000e+00 -5.2047489e-17  1.0900000e-01]
 [ 8.9200000e-02  8.9200000e-02  8.9200000e-02 -3.8000000e-03]],
 R_e : [[ 6.1232343e-17  6.1232343e-17  1.0000000e+00]
 [ 1.0000000e+00 -1.2246469e-16 -6.1232343e-17]
 [ 1.2246469e-16  1.0000000e+00 -6.1232343e-17]],
 p_e : [ 0.89943  0.109   -0.0038 ]
R_i : [[ 6.1232343e-17  6.12

Test ข้อ 1

In [13]:
from FRA333_HW3_6504_6527 import endEffectorJacobianHW3

J = endEffectorJacobianHW3(q)
print(J.round(5))

[[-0.109   -0.109   -0.109  ]
 [ 0.89943  0.89943  0.47443]
 [ 0.       0.       0.     ]
 [ 0.      -0.      -0.     ]
 [ 0.      -0.      -0.     ]
 [ 1.       1.       1.     ]]


Test ข้อ 2

In [14]:
from FRA333_HW3_6504_6527 import checkSingularityHW3

S = checkSingularityHW3(q)
print(S)

True


Test ข้อ 3

In [15]:
from FRA333_HW3_6504_6527 import computeEffortHW3
w = np.array([1,2,3,4,5,6])
w = w.reshape(6,1)

tau = computeEffortHW3(q,w)
print(tau)

[[7.68986]
 [7.68986]
 [6.83986]]
