Test พี่เขา

In [1]:
from HW3_utils import FKHW3
import numpy as np
import math
q = [0,0,0]


In [2]:
R,P,R_e,p_e = FKHW3(q)

print(f"R : {R},\n P : {P},\n R_e : {R_e},\n p_e : {p_e}")

print("=========================================")
print(f"R_i : {R[:,:,3]}")
print("=========================================")
print(f"P_i : {P[:,3]}")

R : [[[-1.0000000e+00 -1.0000000e+00 -1.0000000e+00  6.1232343e-17]
  [-1.2246469e-16 -7.4987988e-33 -7.4987988e-33  6.1232343e-17]
  [ 0.0000000e+00  1.2246469e-16  1.2246469e-16  1.0000000e+00]]

 [[ 1.2246469e-16  1.2246469e-16  1.2246469e-16  1.0000000e+00]
  [-1.0000000e+00 -6.1232343e-17 -6.1232343e-17 -1.2246469e-16]
  [ 0.0000000e+00  1.0000000e+00  1.0000000e+00 -6.1232343e-17]]

 [[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.2246469e-16]
  [ 0.0000000e+00  1.0000000e+00  1.0000000e+00  1.0000000e+00]
  [ 1.0000000e+00  6.1232343e-17  6.1232343e-17 -6.1232343e-17]]],
 P : [[ 0.0000000e+00  0.0000000e+00  4.2500000e-01  8.9943000e-01]
 [ 0.0000000e+00  0.0000000e+00 -5.2047489e-17  1.0900000e-01]
 [ 8.9200000e-02  8.9200000e-02  8.9200000e-02 -3.8000000e-03]],
 R_e : [[ 6.1232343e-17  6.1232343e-17  1.0000000e+00]
 [ 1.0000000e+00 -1.2246469e-16 -6.1232343e-17]
 [ 1.2246469e-16  1.0000000e+00 -6.1232343e-17]],
 p_e : [ 0.89943  0.109   -0.0038 ]
R_i : [[ 6.1232343e-17  6.12

In [3]:
from FRA333_HW3_6504_6527 import endEffectorJacobianHW3

# J_v,J_w = endEffectorJacobianHW3(q)

J = endEffectorJacobianHW3(q)
print(J)

[[0.]
 [0.]
 [1.]]
[ 0.89943  0.109   -0.093  ]


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)